# Generated by Django 5.2.3 on 2025-09-03 00:51

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='nombre', unique=True)),
                ('usuario', models.CharField(max_length=1000, verbose_name='Usuario')),
                ('correo', models.EmailField(max_length=254)),
                ('contraseña', models.CharField(max_length=50)),
                ('celular', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
            },
        ),
    ]
