# Generated by Django 5.2.3 on 2025-09-03 00:51

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de usuario')),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='nombre', unique=True)),
                ('fecha_inscripcion', models.DateField(verbose_name='Fecha de Inscripción')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('tipo_vehiculo', models.CharField(max_length=50, verbose_name='Tipo de vehiculo')),
                ('cobro', models.DecimalField(decimal_places=2, max_digits=10)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
            },
        ),
    ]
