# Generated by Django 5.2.3 on 2025-09-10 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='telefono',
            new_name='celular',
        ),
    ]
