# Generated by Django 5.2.3 on 2025-09-10 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_rename_telefono_cliente_celular'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='empleado',
            field=models.CharField(default='desconocido', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='lugar_registro',
            field=models.CharField(default='ninguno', max_length=100),
            preserve_default=False,
        ),
    ]
