# Generated by Django 5.2.3 on 2025-09-03 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=255)),
                ('mensaje', models.TextField()),
                ('frecuencia', models.CharField(choices=[('diario', 'Diario'), ('semanal', 'Semanal'), ('mensual', 'Mensual'), ('personalizado', 'Personalizado')], default='diario', max_length=20)),
                ('dias_personalizado', models.PositiveIntegerField(blank=True, help_text='Número de días si la frecuencia es personalizada', null=True)),
                ('tipo', models.CharField(choices=[('general', 'General'), ('soat', 'Recordatorio de SOAT')], default='general', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecordatorioSOAT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_recordatorios', models.PositiveIntegerField(default=1)),
                ('dias_antes', models.JSONField(help_text='Lista de días antes del vencimiento para enviar recordatorio')),
                ('mensaje', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recordatorio_soat', to='mensajes.mensaje')),
            ],
        ),
    ]
